## TPAddon by kotyk (@kotyk7)

## User section, something that user will often see
user:
  show-fallback-msg-to-users: true
  gui-name: "TELEPORTATION GUI"
  item-name: "&1Teleportation token"
  token:
    material1: "REDSTONE"
    material2: "STICK"

## Cooldown for /home, /tpa, /tpgui.
cooldown: 30

## Playerheads in /tpgui, texture is not a link and needs to be in Base64 format like provided below.
skin:
  1:
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjE5ZTM2YTg3YmFmMGFjNzYzMTQzNTJmNTlhN2Y2M2JkYjNmNGM4NmJkOWJiYTY5Mjc3NzJjMDFkNGQxIn19fQ=="
    name: "&1Spawn"
  2:
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2Y3Y2RlZWZjNmQzN2ZlY2FiNjc2YzU4NGJmNjIwODMyYWFhYzg1Mzc1ZTlmY2JmZjI3MzcyNDkyZDY5ZiJ9fX0="
    name: "&1Home"

messages:
  prefix: "&6&l(&9&lTPAddon&6&l)&7"
  configReloaded: "Reloaded config."
  unknownCommand: "Unknown command."
  playernotfound: "Player not found."
  tpa:
    usage:
      msg: "Sends a teleportation request to another player."
      command: "/tpa <player name>"
    requests:
      sent: "Sent a teleportation request to %s"
      received: "You received a teleportation request from %s"
    fallback:
      usermsg: "Required dependency is not installed on this server. TPA is disabled."
      adminmsg: "You need to install Essentials to get TPA working."
  token:
    info: "Create the token in the Crafting Table. Recipe should be automatically unlocked."
    noToken: "You don't have a token. Craft one in the Crafting Table!"
    give: "Gave you the teleportation token."
    giveother: "Gave %s a teleportation token."
  cooldown:
    message: "You can use this command again after %s seconds."
    check: "Your cooldown will expire after %s seconds."
    nocooldown: "You don't have cooldown set."
    checkother: "This player has %s seconds to cooldown expire."
  actionbar:
    tptospawn: "&cTeleported you to the spawn!"
    tptohome: "&cTeleported you to your bed!"
    tperror: "&cAn error occured while teleporting! Didn't take your token."

    functionnotdone: "&cThis function is not available yet!"

    cancelplace: "&cYou can't place a teleportation token!"
  gui:
    open: "Opening menu..."
    openother: "Opening the menu for %s"
  home:
    teleported: "&cTeleported you to your bed!"
    nohome: "&cYou don't have a bed!"

## Don't touch me!
plugin:
  version: 1.1