name: TPAddon
description: TPAddon is a plugin that redefines teleportation methods on your server!
main: me.kotyk.TPAddon.Main
version: 1.1
author: kotyk7
website: https://github.com/kotyk7/TPAddon
depend: [Essentials]
api-version: "1.16"

commands:
  tpaddon:
    description: "Basic TPAddon command"
    usage: "/tpaddon <subcommand>"
  tpgui:
    description: "TPAddon teleportation GUI"
    usage: "/tpgui <subcommand>"
    aliases:
      - teleportgui
  tpa:
    description: "Sends a teleportation request to another player"
    usage: "/tpa <player>"
  home:
    description: "Teleports you to your home!"
    usage: "/home"
  spawn:
    description: "Teleports you to the world spawnpoint!"
    usage: "/spawn"
